# Generated by Django 5.2.17 on 2026-09-26 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneGearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveIntegerField(verbose_name='过道号')),
                ('switchedAt', models.DateTimeField(verbose_name='切换时刻')),
                ('gear', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='档位')),
                ('operatorName', models.CharField(max_length=80, verbose_name='操作人')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '过道禁烟档志',
                'verbose_name_plural': '过道禁烟档志',
                'ordering': ['-switchedAt', '-id'],
                'constraints': [models.UniqueConstraint(fields=('lane', 'switchedAt'), name='uniq_lane_gear_minute')],
            },
        ),
    ]
